[package]
name = "native"
version = "0.0.1"
authors = ["Yusuke Sasaki <yusuke.sasaki.nuem@gmail.com>"]
license = "MIT"

[lib]
name = "native"
crate-type = ["dylib"]

[dependencies]
neon = "0.1"

[dependencies.mandelbrot]
path = ".."
