[package]
name = "mandelbrot"
version = "0.0.1"
authors = ["Yusuke Sasaki <yusuke.sasaki.nuem@gmail.com>"]
license = "MIT"

[lib]
name = "mandelbrot"
crate-type = ["dylib"]

[dependencies]
neon = "0.1"
itertools = "*"

[dependencies.base]
path = "../base"
